baseURL = "https://raufzerif.github.io/"
languageCode = 'en-us'
title = 'Abd Raouf Zerkhef'
theme = "hugo-noir"

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags" 

[params]
name = "Abd Raouf Zerkhef"
location = "Algiers, Algeria"
description = "Currently studying Data Science & AI with a passion for Generative AI. I combine backend development (Golang/Gin), mobile app creation (Flutter), and UI/UX design to build innovative, impactful solutions."
github = "https://github.com/raufzer"
github_username = "raufzer"
email = "zerkhefabdraouf@gmail.com"
linkedin = "https://www.linkedin.com/in/raufzer"
linkedin_username = "raufzer"
twitter = "https://www.x.com/raufzer"
twitter_username = "raufzer"
medium = "https://www.medium.com/@raufzer"
instagram = "https://instagram.com/raufzer"
kaggle = "https://www.kaggle.com/johndoe123"
kaggle_username = "raufzer"

[[params.honors]]
institution = "Ipsum Solutions"
title = "Ipsum Solutions"
date = "March 2023"

[[params.honors]]
institution = "Ipsum Solutions"
title = "Ipsum Solutions"
date = "May 2018"

[[params.certifications]]
title = "Ipsum Solutions"
date = "Dec 2024"
url = "https://example.com/cert-azure"

[[params.certifications]]
title = "Ipsum Solutions"
date = "March 2024" 
url = "https://example.com/cert-gcp"

[[params.experience]]
company = "Ipsum Solutions"
role = "Ipsum Solutions"
period = "Jun 2022 - Dec 2022"
description = "Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
responsibilities = [
    "Sed ut perspiciatis unde omnis iste natus error",
    "Nemo enim ipsam voluptatem quia voluptas sit",
    "At vero eos et accusamus et iusto odio dignissimos",
    "Et harum quidem rerum facilis est et expedita"
]

[[params.projects]]
title = "Project Consectetur"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam."
tech = "Golang, TensorFlow, Docker, Redis"
image = "/images/projects/consectetur.png"
link = "https://github.com/loremipsum/consectetur"



[[params.blogs]]
title = "Lorem Ipsum Systems"
date = "2025-03-15"
summary = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem."
tags = ["Lorem", "Ipsum", "Dolor"]
content = """
Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit...
"""
link = "https://medium.com/@loremipsum/lorem-systems"


[[params.voluntary]]
role = "Ipsum Solutions"
organization = "Lorem Foundation"
period = "2020 - Present"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis."

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5
