baseURL = "https://raufzerif.github.io/"
languageCode = 'en-us'
title = 'Abd Raouf Zerkhef'
theme = "hugo-noir"

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags" 

[params]
name = "Abd Raouf Zerkhef"
location = "Algiers, Algeria"
description = "I'm a Data Science & AI student with a strong passion for Generative AI. I combine backend development (Golang/Gin), mobile app creation (Flutter), and UI/UX design to build innovative and impactful digital solutions."
github = "https://github.com/raufzer"
github_username = "raufzer"
email = "zerkhefabdraouf@gmail.com"
linkedin = "https://www.linkedin.com/in/raufzer"
linkedin_username = "raufzer"
twitter = "https://www.x.com/raufzer"
twitter_username = "raufzer"
medium = "https://www.medium.com/@raufzer"
instagram = "https://instagram.com/raufzer"
kaggle = "https://www.kaggle.com/raufzer"
kaggle_username = "raufzer"

[[params.honors]]
institution = ""
title = ""
date = ""

[[params.honors]]
institution = ""
title = ""
date = ""

[[params.certifications]]
title = ""
date = ""
url = ""

[[params.certifications]]
title = ""
date = "" 
url = ""

[[params.experience]]
company = "RetailSpot"
role = "Back End Developer"
period = "May 2025 - Present"
description = "Working on the AdServer project of RetailSpot, a SaaS platform for retail media and advertising, focused on building scalable and high-performance backend services."



[[params.projects]]
title = "Flutter Docs – GDG Algiers"
description = "Contributed detailed documentation on MVVM architecture, routing, and state management in Flutter for GDG Algiers Docs. Helped Flutter developers adopt clean, scalable patterns in production apps."
tech = "Flutter, Dart, Markdown, Git"
image = "/images/gdg-docs.png"
link = ""



[[params.blogs]]
title = ""
date = ""
summary = ""
tags = ["", "", ""]
content = """
"""
link = ""


[[params.voluntary]]
role = ""
organization = ""
period = ""
description = ""

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5
