baseURL = "https://raufzerif.github.io/"
languageCode = 'en-us'
title = 'Abd Raouf Zerkhef'
theme = "hugo-noir"

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "Abd Raouf Zerkhef"
location = "Algiers, Algeria"
description = "Currently studying Data Science & AI with a passion for Generative AI. I combine backend development (Golang/Gin), mobile app creation (Flutter), and UI/UX design to build innovative, impactful solutions."
github = "https://github.com/raufzer"
github_username = "raufzer"
email = "zerkhefabdraouf@gmail.com"
linkedin = "https://www.linkedin.com/in/raufzer"
linkedin_username = "raufzer"


[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5